direction 0
include ruler.dsl
direction 45
include ruler.dsl
direction 90
include ruler.dsl
direction 135
include ruler.dsl
direction 180
include ruler.dsl
direction 225
include ruler.dsl
direction 270
include ruler.dsl
direction 315
include ruler.dsl
